language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo build --verbose --features mysql
    - cargo test --verbose --features mysql

cache: cargo

notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.esper.net:6697#frippy"
    use_notice: true
    skip_join: true
