[package]
name = "frippy"
version = "0.2.0"
authors = ["Jokler <jokler.contact@gmail.com>"]
repository = "https://github.com/Mavulp/frippy"
readme = "README.md"
license = "MIT"
keywords = ["irc", "bot"]
categories = ["network-programming"]
description = "An IRC Bot"

[lib]
name = "frippy"
path = "src/lib.rs"

[[bin]]
name = "frippy"
path = "bin/main.rs"
doc = false

[dependencies]
irc             = "0.12.5"
reqwest         = "0.8.0"
regex           = "0.2.2"
lazy_static     = "0.2.9"
serde           = "1.0.15"
serde_json      = "1.0.3"

plugin_derive = { path = "plugin_derive" }
unicode_names = { git = 'https://github.com/Jokler/unicode_names', branch = 'update-to-latest-unicode' }

clippy = {version = "*", optional = true}
