[package]
name = "frippy"
version = "0.3.1"
authors = ["Jokler <jokler.contact@gmail.com>"]
repository = "https://github.com/Mavulp/frippy"
readme = "README.md"
license = "MIT"
keywords = ["irc", "bot"]
categories = ["network-programming"]
description = "An IRC Bot"

[[bin]]
name = "frippy"
doc = false

[dependencies]
irc             = "0.13.2"
log             = "0.4.1"
time            = "0.1.39"
reqwest         = "0.8.4"
select          = "0.4.2"
regex           = "0.2.6"
lazy_static     = "1.0.0"
serde           = "1.0.27"
serde_json      = "1.0.9"
glob            = "0.2.11"

frippy_derive = { path = "frippy_derive" }
unicode_names = { git = 'https://github.com/Jokler/unicode_names', branch = 'update-to-latest-unicode' }

clippy = {version = "*", optional = true}
