owners = []
nickname = "frippy"
#nick_password = ""
alt_nicks = ["frippy_", "frippy__"]
realname = "frippy"
server = ""
#password = ""
port = 6697
use_ssl = true
#cert_path = "cert.der"
encoding = "UTF-8"
channels = ["#frippy"]
umodes = "+B"
user_info = "IRC Bot"
version = "frippy v0.4.0"
source = "https://github.com/Mavulp/frippy"
#ping_time = 180
#ping_timeout = 10
#burst_window_length = 8
#max_messages_in_burst = 15
#should_ghost = false
#ghost_sequence = []

#[channel_keys]
#"#frippy" = ""

[options]
#disabled_plugins = "Url"
# If no database url is set a HashMap is used
#mysql_url = "mysql://user:password@address/db"
